In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
path = "./newdata/DVSGesture/ibmGestureTrain/user01_fluorescent/0.npy"
events = np.load(path)

In [6]:
print(events.dtype)
print(events.shape)
print("Fields:", events.dtype.names)
print("Shape:", events.shape)
print("Dtype:", events.dtype)
print("First 5 rows:\n", events[:5])


float64
(213025, 4)
Fields: None
Shape: (213025, 4)
Dtype: float64
First 5 rows:
 [[4.9e+01 8.2e+01 0.0e+00 2.8e-02]
 [5.5e+01 9.2e+01 1.0e+00 3.8e-02]
 [5.5e+01 9.2e+01 1.0e+00 3.9e-02]
 [5.5e+01 9.2e+01 1.0e+00 3.9e-02]
 [9.0e+01 9.9e+01 0.0e+00 6.5e-02]]
