This is what my .npy file looks like:


In [10]:
import numpy as np

# Load your gesture file
data = np.load("3.npy", allow_pickle=True)

print("Data shape:", data.shape)   # should be (N,4)
print("First 5 rows:\n", data[:5])

# Print ranges and unique values
print("x range:", data[:,1].min(), data[:,1].max())
print("y range:", data[:,2].min(), data[:,2].max())
print("t range:", data[:,0].min(), data[:,0].max())
print("unique polarities:", np.unique(data[:,3]))

Data shape: (38333, 4)
First 5 rows:
 [[  0.  71. 100.   1.]
 [  0.  49.  75.   1.]
 [  0.  71.  90.   1.]
 [  0.  58.  69.   0.]
 [  0.  48.  68.   0.]]
x range: 0.0 127.0
y range: 0.0 127.0
t range: 0.0 1.0
unique polarities: [0. 1.]


and this is how the original dvs128 .npy file looks like:


In [11]:
import numpy as np

# Load your gesture file
data = np.load("../newdata/DVSGesture/ibmGestureTest/user24_led/3.npy", allow_pickle=True)

print("Data shape:", data.shape)   # should be (N,4)
print("First 5 rows:\n", data[:5])

# Print ranges and unique values
print("x range:", data[:,1].min(), data[:,1].max())
print("y range:", data[:,2].min(), data[:,2].max())
print("t range:", data[:,0].min(), data[:,0].max())
print("unique polarities:", np.unique(data[:,3]))

Data shape: (920134, 4)
First 5 rows:
 [[2.90e+01 1.02e+02 0.00e+00 0.00e+00]
 [1.50e+01 9.90e+01 1.00e+00 6.00e-03]
 [3.50e+01 7.70e+01 1.00e+00 7.00e-03]
 [3.80e+01 9.50e+01 0.00e+00 3.50e-02]
 [5.00e+00 1.14e+02 1.00e+00 3.60e-02]]
x range: 0.0 127.0
y range: 0.0 1.0
t range: 0.0 127.0
unique polarities: [0.000000e+00 6.000000e-03 7.000000e-03 ... 7.557962e+03 7.557979e+03
 7.558006e+03]
