This is what my .npy file looks like:


In [15]:
import numpy as np

data = np.load("3.npy")

print("Data shape:", data.shape)
print("First 5 rows:\n", data[:5])
print()

# CORRECT INTERPRETATION FOR YOUR DATA
x_col      = data[:, 0]
y_col      = data[:, 1]
p_col      = data[:, 2]
t_norm_col = data[:, 3]

print(f"x range      : {x_col.min():.1f} – {x_col.max():.1f}")
print(f"y range      : {y_col.min():.1f} – {y_col.max():.1f}")
print(f"polarity     : {np.unique(p_col)}")
print(f"t_normalized : {t_norm_col.min():.6f} → {t_norm_col.max():.6f}")

Data shape: (38327, 4)
First 5 rows:
 [[ 66. 101.   0.   0.]
 [ 73.  96.   0.   0.]
 [ 50.  74.   1.   0.]
 [ 58.  71.   0.   0.]
 [ 64.  97.   0.   0.]]

x range      : 0.0 – 127.0
y range      : 0.0 – 127.0
polarity     : [0. 1.]
t_normalized : 0.000000 → 1.000000


and this is how the original dvs128 .npy file looks like:


In [16]:
import numpy as np

# Load your gesture file
data = np.load("../newdata/DVSGesture/ibmGestureTest/user24_led/3.npy", allow_pickle=True)

print("Data shape:", data.shape)
print("First 5 rows:\n", data[:5])
print()

# CORRECT INTERPRETATION FOR YOUR DATA
x_col      = data[:, 0]
y_col      = data[:, 1]
p_col      = data[:, 2]
t_norm_col = data[:, 3]

print(f"x range      : {x_col.min():.1f} – {x_col.max():.1f}")
print(f"y range      : {y_col.min():.1f} – {y_col.max():.1f}")
print(f"polarity     : {np.unique(p_col)}")
print(f"t_normalized : {t_norm_col.min():.6f} → {t_norm_col.max():.6f}")

Data shape: (920134, 4)
First 5 rows:
 [[2.90e+01 1.02e+02 0.00e+00 0.00e+00]
 [1.50e+01 9.90e+01 1.00e+00 6.00e-03]
 [3.50e+01 7.70e+01 1.00e+00 7.00e-03]
 [3.80e+01 9.50e+01 0.00e+00 3.50e-02]
 [5.00e+00 1.14e+02 1.00e+00 3.60e-02]]

x range      : 0.0 – 127.0
y range      : 0.0 – 127.0
polarity     : [0. 1.]
t_normalized : 0.000000 → 7558.006000
